packages:
    - ./package
    - ./test

autoInstallPeers: false
strictPeerDependencies: false

catalogs:
    dev:
        react-native-mmkv: 4.3.0
        unstorage: 1.17.5
    peer:
        react-native-mmkv: ^4.3.0
        unstorage: ^1.17.5

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    # config
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    # tsdown
    - "@tsdown/*"
    - "tsdown"
